service: stack-metrics-backend

useDotenv: true

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs16.x
  apiGateway:
    shouldStartNameWithService: true
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  iamRoleStatements:
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    USERS_TABLE_NAME: 'UsersTable-${self:provider.stage}'
functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

package:
  individually: true

resources:
  Resources:
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}

custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn
